---
title: Survival Data
author: ''
date: []
slug: []
categories: []
tags: []
lastmod: '2021-08-06T13:19:08-04:00'
publishdate: '2021-08-06T13:19:08-04:00'
description: ''
weight: 1
---


Data for survival analysis should always include some key information: a categorical indicator of the event occurring, and the follow-up time for each individual. The follow-up time should be a continuous, interval variable from 0 to the maximum follow-up time. Multiple groups should be indicated with a categorical variable. Any other additional covariates can be included in the data set as well, but how you measure these variables is up to you and what you want to do with them. They can be continuous or categorical. Continouous variables can always be collapsed into categorical ones, but categorical variables can not always be expanded into continuous ones.  

We will look at the Veteran Administration Lung Cancer data set from the survival package in R. It comes from a randomized trial of males with advance inoperable lung cancer. They were randomized to standard or a test chemotherapy. The primary outcome was time to death. The follow-up time for the outcome is indicated by the 'time' variable, and the categorical indicator of the event is 'status' (0 = censored, 1 = event occurrence). Another important variable is 'trt', indicating the randomized group covariates collected were the celltype, Karnofsky performance score (0-100, 100 = good), age, time from cancer diagnosis to randomization (in months), and prior therapy receipt. There is no ID variable, but each row indicates one patient. Take some time to get familiar with the structure of the data set.    

```{r simulatedData, echo=FALSE}
library(survival)
library(kableExtra)
data = veteran
data = data[c(3:4, 1, 2, 5:8)]
data$prior[data$prior==10] = 1
kbl(data) %>%
  add_header_above(c("Outcome Variables" = 2, "Treatment Group" = 1, "Covariates" = 5)) %>%
  kable_paper() %>%
  scroll_box(width = "100%", height = "300px")



```


It is a good idea to look at the distribution of 





